### ISSUE TITLE
pos-image could fall back on non-data URI

### ISSUE THREAD

**Issue by josephguillaume** [pod-os/PodOS#38]
pos-image fails to fetch on public URLs without cors enabled, e.g.,

`
 <pos-image src="https://image.tmdb.org/t/p/w500/gCgt1WARPZaXnq523ySQEUKinCs.jpg"></pos-image>
`

In cases like this, it would make sense to not use a data uri. Perhaps this could be detected based on status code from the fetch?
https://github.com/pod-os/PodOS/blob/7d2693a3b47cc3bc837060bc761d5aabf42c2b27/elements/src/components/pos-image/pos-image.tsx#L51

**Comment by angelo-v** [comment]
fixed in the latest version 0.18.0
