### ISSUE TITLE
Restore previous session

### ISSUE THREAD

**Issue by angelo-v** [pod-os/PodOS#8]
As an authenticated user of PodOS browser I want to be able to use my browser bookmarks and work with mutliple tabs without losing my session, or beeing redirected to other URLs, so that I can rely on core browser functionallity without being distracted.

**Acceptance criteria:**

- When signed in in one tab, I can copy/duplicate the tab and I am still signed in on the new tab
- When doing so, the new tab shows the correct resource, I am not redirected to somewhere else
- When I open a bookmark of a protected resource it shows the bookmarked resource, because I am signed in
- When hosting PodOS browser on a Solid Pod, opening a link in a new tab keeps me signed in

**out of scope:**

- For hosted PodOS Browser opening a link in a new tab will navigate away from the app to the original resource URL, which is fine. The session for the target URL is out of control of the app.

**Comment by josephguillaume** [comment]
I understand this is currently blocked at
https://github.com/pod-os/PodOS/blob/f82809f9c597d582b567c3be43d0664379cab009/core/src/authentication/index.ts#L28-L33

For the standalone netlify version this is not an issue, but I understand the acceptance criteria here have a wider scope.

**Comment by angelo-v** [comment]
The session refresh as described in the story is working and fulfilling all the acceptance criteria. Anything going further should move to a new ticket.

**Comment by josephguillaume** [comment]
I'm all for this mostly working solution, but I do want to document here that the acceptance criteria are not met when multiple PodOS apps are served from the same domain. If I am already logged in on another app on the same domain, I will instead be redirected to that app

This doesn't affect https://browser.pod-os.org/ as far as I can tell.

I've opened a new issue https://github.com/pod-os/PodOS/issues/49
In any case, this us the same blocker originally identified. There apparently hasn't been any progress upstream. https://github.com/pod-os/PodOS/issues/8#issuecomment-1625465204

**Comment by angelo-v** [comment]
The user story only refers to a single app (PodOS browser) and for this the acceptance criteria are meat. Thanks for opening the new issue.
